#include <pebble.h>

#define MAIN_LAYER_WIDTH 144
#define MAIN_LAYER_HEIGHT 145

#define HOURS_FIRST_WIDTH 27
#define HOURS_FIRST_HEIGHT 59
#define HOURS_FIRST_X 70
#define HOURS_FIRST_Y 9
  
#define HOURS_LAST_WIDTH 25
#define HOURS_LAST_HEIGHT 55
#define HOURS_LAST_X 109
#define HOURS_LAST_Y 13

#define MINUTES_FIRST_WIDTH 25
#define MINUTES_FIRST_HEIGHT 55
#define MINUTES_FIRST_X 10
#define MINUTES_FIRST_Y 76
  
#define MINUTES_LAST_WIDTH 27
#define MINUTES_LAST_HEIGHT 59
#define MINUTES_LAST_X 42
#define MINUTES_LAST_Y 78