// Created with TexturePacker (http://www.codeandweb.com/texturepacker)
//
// Sprite sheet: spritesheet.png (448 x 114)
//
// $TexturePacker:SmartUpdate:934ba6d176a286f1b6a540bd4c707f11:41c870d11d07f924091a8f69f720def2:f255187afaed5e6299dc3d2f34bbb167$

#include <pebble.h>

typedef enum {
  INVALID_SPRITE = 0,
  SPRITE_ID_DIGIT_0_0,
  SPRITE_ID_DIGIT_0_1,
  SPRITE_ID_DIGIT_0_2,
  SPRITE_ID_DIGIT_1_0,
  SPRITE_ID_DIGIT_1_1,
  SPRITE_ID_DIGIT_1_2,
  SPRITE_ID_DIGIT_1_3,
  SPRITE_ID_DIGIT_1_4,
  SPRITE_ID_DIGIT_1_5,
  SPRITE_ID_DIGIT_1_6,
  SPRITE_ID_DIGIT_1_7,
  SPRITE_ID_DIGIT_1_8,
  SPRITE_ID_DIGIT_1_9,
  SPRITE_ID_DIGIT_2_0,
  SPRITE_ID_DIGIT_2_1,
  SPRITE_ID_DIGIT_2_2,
  SPRITE_ID_DIGIT_2_3,
  SPRITE_ID_DIGIT_2_4,
  SPRITE_ID_DIGIT_2_5,
  SPRITE_ID_DIGIT_3_0,
  SPRITE_ID_DIGIT_3_1,
  SPRITE_ID_DIGIT_3_2,
  SPRITE_ID_DIGIT_3_3,
  SPRITE_ID_DIGIT_3_4,
  SPRITE_ID_DIGIT_3_5,
  SPRITE_ID_DIGIT_3_6,
  SPRITE_ID_DIGIT_3_7,
  SPRITE_ID_DIGIT_3_8,
  SPRITE_ID_DIGIT_3_9,
  SPRITE_ID_MELTED_CORNER_0_1_BOTTOM_LEFT,
  SPRITE_ID_MELTED_CORNER_0_1_TOP_LEFT,
  SPRITE_ID_MELTED_CORNER_GENERIC_TOP_RIGHT,
  SPRITE_ID_MELTED_EXT_0_LEFT_TOP,
  SPRITE_ID_MELTED_EXT_0_TOP_RIGHT,
  SPRITE_ID_MELTED_EXT_1_RIGHT_BOTTOM,
  SPRITE_ID_MELTED_EXT_1_RIGHT_CENTER,
  SPRITE_ID_MELTED_EXT_1_RIGHT_TOP,
  SPRITE_ID_MELTED_EXT_1_TOP_LEFT,
  SPRITE_ID_MELTED_EXT_2_BOTTOM_RIGHT,
  SPRITE_ID_MELTED_EXT_2_LEFT_BOTTOM,
  SPRITE_ID_MELTED_EXT_2_LEFT_CENTER,
  SPRITE_ID_MELTED_EXT_2_LEFT_TOP,
  SPRITE_ID_MELTED_EXT_3_BOTTOM_RIGHT,
  SPRITE_ID_MELTED_EXT_3_RIGHT_BOTTOM,
  SPRITE_ID_MELTED_EXT_3_RIGHT_CENTER,
  SPRITE_ID_MELTED_EXT_3_RIGHT_TOP,
  SPRITE_ID_MELTED_HORIZLINE_0_1_TOP,
} SpriteId;

GBitmap* gbitmap_create_with_sprite(SpriteId sprite_id);
void destroy_sprite();
