// Created with TexturePacker (http://www.codeandweb.com/texturepacker)
//
// Sprite sheet: spritesheet.png (448 x 114)
//
// $TexturePacker:SmartUpdate:578ac146894a317c45885a5b00c4bf2b:41c870d11d07f924091a8f69f720def2:f255187afaed5e6299dc3d2f34bbb167$

#include <pebble.h>

typedef enum {
  INVALID_SPRITE = 0,
  SPRITE_ID_DIGIT0_0,
  SPRITE_ID_DIGIT0_1,
  SPRITE_ID_DIGIT0_2,
  SPRITE_ID_DIGIT1_0,
  SPRITE_ID_DIGIT1_1,
  SPRITE_ID_DIGIT1_2,
  SPRITE_ID_DIGIT1_3,
  SPRITE_ID_DIGIT1_4,
  SPRITE_ID_DIGIT1_5,
  SPRITE_ID_DIGIT1_6,
  SPRITE_ID_DIGIT1_7,
  SPRITE_ID_DIGIT1_8,
  SPRITE_ID_DIGIT1_9,
  SPRITE_ID_DIGIT2_0,
  SPRITE_ID_DIGIT2_1,
  SPRITE_ID_DIGIT2_2,
  SPRITE_ID_DIGIT2_3,
  SPRITE_ID_DIGIT2_4,
  SPRITE_ID_DIGIT2_5,
  SPRITE_ID_DIGIT3_0,
  SPRITE_ID_DIGIT3_1,
  SPRITE_ID_DIGIT3_2,
  SPRITE_ID_DIGIT3_3,
  SPRITE_ID_DIGIT3_4,
  SPRITE_ID_DIGIT3_5,
  SPRITE_ID_DIGIT3_6,
  SPRITE_ID_DIGIT3_7,
  SPRITE_ID_DIGIT3_8,
  SPRITE_ID_DIGIT3_9,
  SPRITE_ID_MELTED_CORNER_0_1_BOTTOM_LEFT,
  SPRITE_ID_MELTED_CORNER_0_1_TOP_LEFT,
  SPRITE_ID_MELTED_CORNER_GENERIC_TOP_RIGHT,
  SPRITE_ID_MELTED_EXT0_LEFT_TOP,
  SPRITE_ID_MELTED_EXT0_TOP_RIGHT,
  SPRITE_ID_MELTED_EXT1_RIGHT_BOTTOM,
  SPRITE_ID_MELTED_EXT1_RIGHT_CENTER,
  SPRITE_ID_MELTED_EXT1_RIGHT_TOP,
  SPRITE_ID_MELTED_EXT1_TOP_LEFT,
  SPRITE_ID_MELTED_EXT2_BOTTOM_RIGHT,
  SPRITE_ID_MELTED_EXT2_LEFT_BOTTOM,
  SPRITE_ID_MELTED_EXT2_LEFT_CENTER,
  SPRITE_ID_MELTED_EXT2_LEFT_TOP,
  SPRITE_ID_MELTED_EXT3_BOTTOM_RIGHT,
  SPRITE_ID_MELTED_EXT3_RIGHT_BOTTOM,
  SPRITE_ID_MELTED_EXT3_RIGHT_CENTER,
  SPRITE_ID_MELTED_EXT3_RIGHT_TOP,
  SPRITE_ID_MELTED_HORIZLINE_0_1_TOP,
} SpriteId;

GBitmap* gbitmap_create_with_sprite(SpriteId sprite_id);
void destroy_sprite();
